// Multi-harness emit golden (ADR-0013 golden-first · ADR-0066 engine-neutral emitter). Pins the
// BYTE-STABLE per-harness bundle the agent-dev emitter (T19) must render from ONE typed Caisson
// schema: `.claude/` for Claude Code (agents/skills/rules + a hooks manifest), a single aggregated
// `AGENTS.md` for Codex, and per-artifact `.cursor/rules/*.mdc` for Cursor. The binding contract
// (ADR-0066) the committed tree enforces: Claude Code is ONE emit target among several — no harness
// is the substrate, and the same schema fans out to every harness shape.
//
// Golden-first (ADR-0013): this fixture + its test land BEFORE the emitter logic. `produce` ECHOES
// the authored `EXPECTED_BUNDLE` — it does NOT import the not-yet-built `emitter.ts` (which would
// fail the whole suite to RESOLVE rather than assert a contract). T19 rewires `produce` to
// `renderHarnessBundles(EMIT_INPUT)`; the committed `src/__golden__/emit/` tree (frozen here) then
// enforces byte-equality with BLESS unset — the live emitter must reproduce it exactly.
import { parseArtifact, type Artifact } from "@caisson/agent-kernel";
import { defineModuleGolden } from "@caisson/testing/golden-module";

/** A lifecycle hook binding: a `${phase}:${act}` point handled by a named artifact in the bundle. */
export interface EmitHookBinding {
  readonly on: string;
  readonly use: string;
}

/** The ONE typed schema the multi-harness emitter renders (the engine-neutral source of truth). */
export interface EmitInput {
  readonly artifacts: readonly Artifact[];
  readonly hooks: readonly EmitHookBinding[];
}

/** One emitted file: a bundle-relative POSIX path and its byte-stable text content. */
export interface EmittedFile {
  readonly path: string;
  readonly content: string;
}

/** The full multi-harness bundle: every emitted file (matched against the committed golden tree). */
export interface EmittedBundle {
  readonly files: readonly EmittedFile[];
}

// ── Shared artifact prose (DRY: each datum is rendered once per harness; keeping it in one constant
// guarantees the cross-harness bytes agree and the input round-trips the agent-kernel schema). ──────
const REVIEWER_DESC = "Reviews a diff for correctness and the security floor.";
const REVIEWER_INVOKE =
  "A bounded diff needs an idiom + security pass before SHIP.";
const GUIDED_DESC =
  "Execute a written plan task-by-task with review checkpoints.";
const RULE_DESC =
  "Production code may not use `any` or silence a real type error.";

// The fixed input: one curated agent + skill + rule, validated through the agent-kernel `.strict()`
// schema (a mis-shaped artifact throws here, never reaches the emitter), plus two lifecycle hook
// bindings naming the in-bundle reviewer agent.
const EMIT_ARTIFACTS: readonly Artifact[] = [
  {
    kind: "agent",
    name: "code-reviewer",
    description: REVIEWER_DESC,
    capabilities: ["code_review", "security_audit"],
    tools: ["read", "grep", "bash"],
    whenToInvoke: REVIEWER_INVOKE,
  },
  {
    kind: "skill",
    name: "guided-execution",
    description: GUIDED_DESC,
    trigger: "user",
    steps: [
      "dispatch a fresh subagent per task",
      "review the diff",
      "unblock the next task",
    ],
  },
  {
    kind: "rule",
    name: "no-any-in-prod",
    description: RULE_DESC,
    severity: "error",
  },
].map(parseArtifact);

export const EMIT_INPUT: EmitInput = {
  artifacts: EMIT_ARTIFACTS,
  hooks: [
    { on: "before:execute", use: "code-reviewer" },
    { on: "before:ship", use: "code-reviewer" },
  ],
};

// ── Claude Code bundle: one file per artifact under `.claude/{agents,skills,rules}/` + a hooks
// manifest. Frontmatter carries the typed fields; the body is human-readable guidance. ─────────────
const CLAUDE_AGENT = `---
name: code-reviewer
description: ${REVIEWER_DESC}
capabilities:
  - code_review
  - security_audit
tools:
  - read
  - grep
  - bash
---

${REVIEWER_DESC}

When to invoke: ${REVIEWER_INVOKE}
`;

const CLAUDE_SKILL = `---
name: guided-execution
description: ${GUIDED_DESC}
trigger: user
---

${GUIDED_DESC}

Steps:
1. dispatch a fresh subagent per task
2. review the diff
3. unblock the next task
`;

const CLAUDE_RULE = `---
name: no-any-in-prod
description: ${RULE_DESC}
severity: error
---

${RULE_DESC}
`;

const CLAUDE_HOOKS = `{
  "version": 1,
  "hooks": [
    {
      "on": "before:execute",
      "use": "code-reviewer"
    },
    {
      "on": "before:ship",
      "use": "code-reviewer"
    }
  ]
}
`;

// ── Codex bundle: ONE aggregated `AGENTS.md` (Codex's single-file convention). ─────────────────────
const CODEX_AGENTS = `# AGENTS

Generated by @caisson/agent-dev from one typed Caisson schema (Codex harness).

## Agents

### code-reviewer

${REVIEWER_DESC}

- Capabilities: code_review, security_audit
- Tools: read, grep, bash
- When to invoke: ${REVIEWER_INVOKE}

## Skills

### guided-execution

${GUIDED_DESC}

1. dispatch a fresh subagent per task
2. review the diff
3. unblock the next task

## Rules

### no-any-in-prod (error)

${RULE_DESC}
`;

// ── Cursor bundle: one MDC project rule per artifact under `.cursor/rules/`. Rules always apply;
// agent/skill guidance is opt-in (`alwaysApply: false`). ───────────────────────────────────────────
const CURSOR_AGENT = `---
description: ${REVIEWER_DESC}
alwaysApply: false
---

# code-reviewer (agent)

${REVIEWER_DESC}

- Capabilities: code_review, security_audit
- Tools: read, grep, bash
- When to invoke: ${REVIEWER_INVOKE}
`;

const CURSOR_SKILL = `---
description: ${GUIDED_DESC}
alwaysApply: false
---

# guided-execution (skill)

${GUIDED_DESC}

1. dispatch a fresh subagent per task
2. review the diff
3. unblock the next task
`;

const CURSOR_RULE = `---
description: ${RULE_DESC}
alwaysApply: true
---

# no-any-in-prod (rule, error)

${RULE_DESC}
`;

/**
 * The authored byte-stable bundle (the contract `src/__golden__/emit/` freezes). The same three
 * artifacts fan out to all three harness shapes — proving no single harness is the substrate.
 */
const EXPECTED_BUNDLE: EmittedBundle = {
  files: [
    { path: ".claude/agents/code-reviewer.md", content: CLAUDE_AGENT },
    { path: ".claude/skills/guided-execution.md", content: CLAUDE_SKILL },
    { path: ".claude/rules/no-any-in-prod.md", content: CLAUDE_RULE },
    { path: ".claude/hooks.json", content: CLAUDE_HOOKS },
    { path: "AGENTS.md", content: CODEX_AGENTS },
    { path: ".cursor/rules/code-reviewer.mdc", content: CURSOR_AGENT },
    { path: ".cursor/rules/guided-execution.mdc", content: CURSOR_SKILL },
    { path: ".cursor/rules/no-any-in-prod.mdc", content: CURSOR_RULE },
  ],
};

export const agentDevGolden = defineModuleGolden({
  module: "@caisson/agent-dev",
  goldenDir: "src/__golden__",
  cases: [
    {
      name: "emit",
      input: EMIT_INPUT,
      // Golden-first echo (ADR-0013). T19 rewires this to `renderHarnessBundles(input)`; the
      // committed `__golden__/emit/` tree then enforces the emitter reproduces it byte-for-byte.
      produce: () => EXPECTED_BUNDLE,
    },
  ],
});
