// The generator core (ADR-0048/0021/0004). Validates a buyer's selection against the registry
// ALLOWLIST — every module id AND version — BEFORE any path construction or subprocess, then
// materializes a workspace via a deterministic engine seam (in-repo template copy + typed transform,
// ADR-0048). The default engine is now `templatesEngine` (the real templated drive, ADR-0068/0072):
// it reads the in-repo `templates/` tree and emits the buyer repo. The disk write (FileSetWriter)
// + buyer MCP plug in behind the same seam (a separate task).
import {
  type RegistryIndex,
  assertKnownModule,
  assertKnownVersion,
} from "@caisson/registry-schema";
import { templatesEngine } from "./engine-templates.ts";
import {
  type GeneratedFile,
  type GeneratedFileSet,
  type GeneratorEngine,
  Selection,
} from "./seam.ts";

// Re-export the generator contract from its leaf module so external importers keep importing the
// `Selection` schema/type + the engine seam types from `@caisson/cli` (via `./generate.ts`)
// unchanged. The declarations live in `seam.ts` to keep engine implementations off a build cycle.
export {
  type GeneratedFile,
  type GeneratedFileSet,
  type GeneratorEngine,
  Selection,
} from "./seam.ts";

/**
 * Parse + ALLOWLIST-GATE a raw selection. Zod `.strict()` first, then every module id + version is
 * validated against the registry index (`assertKnownModule` re-asserts the slug regex;
 * `assertKnownVersion` blocks a raw version reaching a path). Throws BEFORE any side effect — the
 * generator must never construct a path or spawn a subprocess for an unknown module.
 */
export function validateSelection(
  index: RegistryIndex,
  raw: unknown,
): Selection {
  const selection = Selection.parse(raw);
  for (const m of selection.modules) {
    assertKnownModule(index, m.id);
    assertKnownVersion(index, m.id, m.version);
  }
  return selection;
}

/**
 * The legacy minimal skeleton engine (Wave 0): a 3-file workspace that INSTALLS the selected
 * modules from the registry (it never copies module source). Superseded as the default by
 * `templatesEngine` (the real templated drive, ADR-0068), but kept exported because the test suite
 * and the spy-engine harness reference it. No network, no fs — pure construction.
 */
export const defaultEngine: GeneratorEngine = {
  materialize(selection: Selection): GeneratedFileSet {
    const deps = Object.fromEntries(
      [...selection.modules]
        .map((m) => [m.id, m.version] as const)
        .sort((a, b) => (a[0] < b[0] ? -1 : 1)),
    );
    const pkg = {
      name: selection.projectName,
      private: true,
      type: "module",
      ...(selection.edition ? { caissonEdition: selection.edition } : {}),
      dependencies: deps,
    };
    const files: GeneratedFile[] = [
      { path: "package.json", content: `${JSON.stringify(pkg, null, 2)}\n` },
      // Modules install from registry.caisson.sh under the @caisson scope (ADR-0223 read path).
      {
        path: ".npmrc",
        content:
          "@caisson:registry=https://registry.caisson.sh\n//registry.caisson.sh/:_authToken=${CAISSON_LICENSE_TOKEN}\n",
      },
      {
        path: "README.md",
        content: readme(selection),
      },
    ];
    return [...files].sort((a, b) => (a.path < b.path ? -1 : 1));
  },
};

function readme(selection: Selection): string {
  const lines = [
    `# ${selection.projectName}`,
    "",
    selection.edition
      ? `Generated by \`create-caisson\` — the **${selection.edition}** edition.`
      : "Generated by `create-caisson`.",
    "",
    "## Modules",
    "",
    ...[...selection.modules]
      .sort((a, b) => (a.id < b.id ? -1 : 1))
      .map((m) => `- \`${m.id}\` @ ${m.version}`),
    "",
  ];
  return `${lines.join("\n")}\n`;
}

/**
 * Validate (allowlist) then materialize. Validation runs FIRST, so an unknown id/version throws
 * before the engine is ever invoked (a spy engine is never called on a bad selection). Returns the
 * file set in memory — Wave 0 does not write to disk (the P5 writer is a separate, injected seam).
 */
export function generate(
  index: RegistryIndex,
  raw: unknown,
  engine: GeneratorEngine = templatesEngine,
): { selection: Selection; files: GeneratedFileSet } {
  const selection = validateSelection(index, raw);
  return { selection, files: engine.materialize(selection) };
}
