// The generator core (ADR-0048/0021/0004). Validates a buyer's selection against the registry
// ALLOWLIST — every module id AND version — BEFORE any path construction or subprocess, then
// materializes a workspace via a deterministic engine seam (in-repo template copy + typed transform,
// ADR-0048). Wave 0 ships the validation gate + the seam + a deterministic skeleton (golden-fixtured);
// the full P5 generation drive (disk write + MCP) plugs in behind the same seam.
import { z } from "zod";
import {
  type RegistryIndex,
  assertKnownModule,
  assertKnownVersion,
} from "@caisson/registry";

const EDITIONS = ["compliance", "ai-kit", "local-ai", "agent-dev"] as const;

const ModuleSelection = z
  .object({
    id: z.string(),
    version: z.string(),
  })
  .strict();

/** A buyer's selection. Project name is a strict slug (it becomes a directory at P5 — no traversal). */
export const Selection = z
  .object({
    projectName: z
      .string()
      .min(1)
      .max(64)
      .regex(/^[a-z0-9][a-z0-9-]*$/, "must be a lowercase slug"),
    edition: z.enum(EDITIONS).optional(),
    modules: z.array(ModuleSelection).min(1),
  })
  .strict();
export type Selection = z.infer<typeof Selection>;

export interface GeneratedFile {
  /** Relative path within the generated repo. Always a fixed literal here — never built from input. */
  readonly path: string;
  readonly content: string;
}
export type GeneratedFileSet = readonly GeneratedFile[];

/** The generator engine seam (ADR-0048). Swap the deterministic copy/transform for ts-morph later. */
export interface GeneratorEngine {
  materialize(selection: Selection): GeneratedFileSet;
}

/**
 * Parse + ALLOWLIST-GATE a raw selection. Zod `.strict()` first, then every module id + version is
 * validated against the registry index (`assertKnownModule` re-asserts the slug regex;
 * `assertKnownVersion` blocks a raw version reaching a path). Throws BEFORE any side effect — the
 * generator must never construct a path or spawn a subprocess for an unknown module.
 */
export function validateSelection(
  index: RegistryIndex,
  raw: unknown,
): Selection {
  const selection = Selection.parse(raw);
  for (const m of selection.modules) {
    assertKnownModule(index, m.id);
    assertKnownVersion(index, m.id, m.version);
  }
  return selection;
}

/**
 * The default deterministic engine: assembles a workspace that INSTALLS the selected modules from
 * the registry (it never copies module source). Output is a fixed file set for a fixed selection
 * (golden-fixtured, ADR-0021 §golden). No network, no fs — pure construction.
 */
export const defaultEngine: GeneratorEngine = {
  materialize(selection: Selection): GeneratedFileSet {
    const deps = Object.fromEntries(
      [...selection.modules]
        .map((m) => [m.id, m.version] as const)
        .sort((a, b) => (a[0] < b[0] ? -1 : 1)),
    );
    const pkg = {
      name: selection.projectName,
      private: true,
      type: "module",
      ...(selection.edition ? { caissonEdition: selection.edition } : {}),
      dependencies: deps,
    };
    const files: GeneratedFile[] = [
      { path: "package.json", content: `${JSON.stringify(pkg, null, 2)}\n` },
      // Modules install from GitHub Packages under the @caisson scope (ADR-0047/0021 read path).
      {
        path: ".npmrc",
        content: "@caisson:registry=https://npm.pkg.github.com\n",
      },
      {
        path: "README.md",
        content: readme(selection),
      },
    ];
    return [...files].sort((a, b) => (a.path < b.path ? -1 : 1));
  },
};

function readme(selection: Selection): string {
  const lines = [
    `# ${selection.projectName}`,
    "",
    selection.edition
      ? `Generated by \`create-caisson\` — the **${selection.edition}** edition.`
      : "Generated by `create-caisson`.",
    "",
    "## Modules",
    "",
    ...[...selection.modules]
      .sort((a, b) => (a.id < b.id ? -1 : 1))
      .map((m) => `- \`${m.id}\` @ ${m.version}`),
    "",
  ];
  return `${lines.join("\n")}\n`;
}

/**
 * Validate (allowlist) then materialize. Validation runs FIRST, so an unknown id/version throws
 * before the engine is ever invoked (a spy engine is never called on a bad selection). Returns the
 * file set in memory — Wave 0 does not write to disk (the P5 writer is a separate, injected seam).
 */
export function generate(
  index: RegistryIndex,
  raw: unknown,
  engine: GeneratorEngine = defaultEngine,
): { selection: Selection; files: GeneratedFileSet } {
  const selection = validateSelection(index, raw);
  return { selection, files: engine.materialize(selection) };
}
