// EU-AI-Act evidence-path sample (ADR-0095 W3) — Apache-2.0, generated by `create-caisson`.
//
// Demonstrates the SHAPE of Caisson's evidence path end to end, using only OPEN primitives:
//   1. APPEND  — a tiny evidence record per automated decision (EU AI Act Art. 12 record-keeping).
//   2. CHAIN   — SHA-256 hash-chain the records via the Apache-2.0 `@caisson/kernel` audit-chain
//                (`buildChain`/`anchorChain`/`verifyChain` — tamper-evident linkage).
//   3. SIGN    — a detached Ed25519 signature (bare `node:crypto`) over the chain's anchor, binding
//                the chain to a key holder at a point in time.
//   4. VERIFY  — recompute the chain and re-verify the signature; both must pass.
//
// This is a SAMPLE, not the product: no WORM store, no evidence-pack generator, no compliance
// control catalogue. The full evidence-pack pipeline (versioned packs, control mapping, retention
// policy) ships in the commercial Compliance edition — this file imports NOTHING from it.
import { anchorChain, buildChain, verifyChain } from "@caisson/kernel/node";
import type {
  AuditChainAnchor,
  AuditChainEntry,
  ChainVerification,
  JsonValue,
} from "@caisson/kernel";
import {
  generateKeyPairSync,
  sign as cryptoSign,
  verify as cryptoVerify,
} from "node:crypto";

/**
 * One automated-decision record (EU AI Act Art. 12 flavor) — deliberately tiny. The index
 * signature matches `@caisson/kernel`'s `JsonValue` so a list of these can be folded straight into
 * `buildChain` without a cast.
 */
export interface EvidenceRecord {
  readonly [key: string]: JsonValue;
  readonly event: string;
  readonly actorId: string;
  readonly timestamp: string;
  readonly details: Readonly<Record<string, JsonValue>>;
}

export interface EvidencePathResult {
  readonly chain: readonly AuditChainEntry[];
  readonly anchor: AuditChainAnchor;
  readonly chainVerification: ChainVerification;
  /** Detached Ed25519 signature over the chain's anchor, hex-encoded (64 bytes → 128 hex chars). */
  readonly signature: string;
  readonly signatureValid: boolean;
}

/** A fixed, illustrative sequence of evidence records — three steps of one automated decision. */
export const SAMPLE_EVIDENCE: readonly EvidenceRecord[] = [
  {
    event: "model.invoked",
    actorId: "system:eligibility-scorer",
    timestamp: "2026-06-30T12:00:00.000Z",
    details: { inputHash: "a1b2c3", modelVersion: "1.4.0" },
  },
  {
    event: "decision.rendered",
    actorId: "system:eligibility-scorer",
    timestamp: "2026-06-30T12:00:01.000Z",
    details: { outcome: "denied", confidence: 0.91 },
  },
  {
    event: "human.reviewed",
    actorId: "user:reviewer-7",
    timestamp: "2026-06-30T12:05:00.000Z",
    details: { upheld: true },
  },
];

/**
 * Build the hash-chain + Ed25519 signature over `records`, then verify both. Pure + sync — no I/O,
 * no env, no network. A fresh Ed25519 keypair is minted per call (a real deployment loads/persists
 * a signing identity instead — out of scope for this sample).
 */
export function runEvidencePathDemo(
  records: readonly EvidenceRecord[] = SAMPLE_EVIDENCE,
): EvidencePathResult {
  // 1+2. APPEND + CHAIN — fold the records into a SHA-256 hash chain (kernel audit-chain).
  const chain = buildChain(records);
  const anchor = anchorChain(chain);
  const chainVerification = verifyChain(chain, anchor);

  // 3. SIGN — a detached Ed25519 signature over the chain's anchor (binds the chain to a key holder).
  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  const message = Buffer.from(JSON.stringify(anchor), "utf8");
  const signature = cryptoSign(null, message, privateKey);

  // 4. VERIFY — recompute + re-verify; a forged anchor or a mismatched key fails here.
  const signatureValid = cryptoVerify(null, message, publicKey, signature);

  return {
    chain,
    anchor,
    chainVerification,
    signature: signature.toString("hex"),
    signatureValid,
  };
}

if (import.meta.main) {
  const result = runEvidencePathDemo();
  process.stdout.write(
    `evidence-path: ${result.chain.length} records chained, ` +
      `chain ${result.chainVerification.valid ? "VALID" : "BROKEN"}, ` +
      `signature ${result.signatureValid ? "VALID" : "INVALID"}\n`,
  );
  if (!result.chainVerification.valid || !result.signatureValid) {
    process.exitCode = 1;
  }
}
