// Compliance attestations (ADR-0181): fill the OSCAL manual-attestation slots the automated
// collectors can't — a human attests each out-of-band artifact (policy PDF, Object-Lock config,
// pentest report) per framework. Attestations persist tenant-scoped under `withTenant` (RLS). The
// full validate-conformant OSCAL SAR+POA&M export (JSON + XML) is generated by the Compliance bundle
// evidence leg from these filled slots; this page owns the human-fill half of that seam.
import type { Metadata } from "next";
import { revalidatePath } from "next/cache";
import { assertCanManageMembers } from "@caisson/org-controls";
import {
  Button,
  Card,
  FormField,
  Icon,
  StatusChip,
} from "@caisson/ui/components";
import {
  AttestationInput,
  COMPLIANCE_FRAMEWORKS,
  attestSlot,
  clearSlot,
  listAttestations,
} from "@/lib/attestations";
import { isOwner, requireDashboardSession } from "@/lib/auth";

export const metadata: Metadata = { title: "Compliance" };

const PATH = "/dashboard/compliance";

async function attestAction(formData: FormData): Promise<void> {
  "use server";
  const session = await requireDashboardSession(PATH);
  // Owner-only: compliance attestations are org-governance evidence that feeds the
  // customer-facing OSCAL SAR/POA&M export — a `seat` must not fabricate or overwrite them. Throws
  // AuthzError (fail-closed) if a seat crafts the POST directly; the UI hides the form from seats.
  assertCanManageMembers(session.role);
  const parsed = AttestationInput.safeParse({
    framework: formData.get("framework"),
    slotId: formData.get("slotId"),
    note: formData.get("note") ?? "",
  });
  if (!parsed.success) return;
  await attestSlot(session.accountId, session.userId, parsed.data);
  revalidatePath(PATH);
}

async function clearAction(formData: FormData): Promise<void> {
  "use server";
  const session = await requireDashboardSession(PATH);
  // Owner-only: clearing an attestation is the destructive, evidence-tampering half.
  assertCanManageMembers(session.role);
  const parsed = AttestationInput.pick({
    framework: true,
    slotId: true,
  }).safeParse({
    framework: formData.get("framework"),
    slotId: formData.get("slotId"),
  });
  if (!parsed.success) return;
  await clearSlot(session.accountId, parsed.data.framework, parsed.data.slotId);
  revalidatePath(PATH);
}

export default async function DashboardCompliancePage() {
  const session = await requireDashboardSession(PATH);
  // Owner-only management (ADR-0176): seats see attestation state read-only; only an
  // owner gets the attest/clear forms. The server actions enforce the same gate (defense-in-depth).
  const owner = isOwner(session);

  // One tenant-scoped read per framework (three frameworks, ADR-0181).
  const filledByFramework = new Map<string, Map<string, string>>();
  for (const fw of COMPLIANCE_FRAMEWORKS) {
    const records = await listAttestations(session.accountId, fw.id);
    filledByFramework.set(
      fw.id,
      new Map(records.map((r) => [r.slotId, r.note])),
    );
  }

  return (
    <div style={{ display: "grid", gap: "var(--cs-space-8)" }}>
      <div>
        <h1
          className="cs-card-title"
          style={{ fontSize: "var(--cs-text-2xl)" }}
        >
          Compliance attestations
        </h1>
        <p className="cs-muted" style={{ marginTop: "var(--cs-space-2)" }}>
          Attest the human-provided evidence the automated collectors can&apos;t
          gather. These fill the OSCAL export&apos;s manual slots. The full SAR
          + POA&amp;M bundle (JSON, and XML where the OSCAL CLI is available) is
          generated by the Compliance bundle from these attestations —{" "}
          <a
            href="/api/compliance/attestations"
            style={{ color: "var(--cs-accent)" }}
          >
            download your attestation record (JSON)
          </a>
          .
        </p>
      </div>

      {COMPLIANCE_FRAMEWORKS.map((fw) => {
        const filled =
          filledByFramework.get(fw.id) ?? new Map<string, string>();
        return (
          // One card per framework (was an unbounded <section>) — a clear break between
          // the three frameworks instead of an h2 floating over an unbroken run of gaps.
          <Card
            key={fw.id}
            style={{ display: "grid", gap: "var(--cs-space-4)" }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "var(--cs-space-3)",
              }}
            >
              <h2
                className="cs-card-title"
                style={{ fontSize: "var(--cs-text-lg)", margin: 0 }}
              >
                {fw.title}
              </h2>
              <StatusChip
                label={`${String(filled.size)} / ${String(fw.slots.length)} attested`}
                tone={filled.size === fw.slots.length ? "accent" : "muted"}
                dot
              />
            </div>

            {fw.slots.map((slot, i) => {
              const isFilled = filled.has(slot.id);
              const note = filled.get(slot.id) ?? "";
              return (
                // A plain row + top divider, not another bordered box — the framework
                // already owns one card; nesting a card per slot inside it would double
                // the boxing (impeccable layout.md: never nest cards inside cards).
                <div
                  key={slot.id}
                  style={{
                    display: "grid",
                    gap: "var(--cs-space-2)",
                    paddingTop: i === 0 ? undefined : "var(--cs-space-4)",
                    borderTop:
                      i === 0 ? undefined : "1px solid var(--cs-border)",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "var(--cs-space-3)",
                    }}
                  >
                    <StatusChip
                      label={isFilled ? "attested" : "pending"}
                      tone={isFilled ? "accent" : "muted"}
                      dot
                    />
                    <span style={{ fontWeight: 500 }}>{slot.label}</span>
                  </div>

                  {owner ? (
                    <form
                      action={attestAction}
                      style={{
                        display: "flex",
                        gap: "var(--cs-space-3)",
                        alignItems: "flex-end",
                        flexWrap: "wrap",
                      }}
                    >
                      <input type="hidden" name="framework" value={fw.id} />
                      <input type="hidden" name="slotId" value={slot.id} />
                      <FormField
                        label="Attestation note / artifact reference"
                        style={{ flex: 1 }}
                      >
                        <input
                          name="note"
                          defaultValue={note}
                          maxLength={2000}
                          placeholder="e.g. link to the signed policy PDF, ticket, or reviewer + date"
                        />
                      </FormField>
                      <Button type="submit" variant="primary">
                        {isFilled ? "Update" : "Attest"}
                      </Button>
                    </form>
                  ) : (
                    // Seats (ADR-0176) see the attested note read-only — owner-only management.
                    // The pending case gets a lock glyph (never colour-alone) so it visually
                    // reads as "gated", not just as thinner body copy.
                    <p
                      className="cs-muted"
                      style={{
                        margin: 0,
                        display: "flex",
                        alignItems: "center",
                        gap: "var(--cs-space-2)",
                      }}
                    >
                      {isFilled ? (
                        note === "" ? (
                          "Attested."
                        ) : (
                          note
                        )
                      ) : (
                        <>
                          <Icon name="lock" size="md" />
                          Only the account owner can attest.
                        </>
                      )}
                    </p>
                  )}

                  {owner && isFilled && (
                    <form action={clearAction}>
                      <input type="hidden" name="framework" value={fw.id} />
                      <input type="hidden" name="slotId" value={slot.id} />
                      <Button type="submit" variant="ghost">
                        Clear attestation
                      </Button>
                    </form>
                  )}
                </div>
              );
            })}
          </Card>
        );
      })}
    </div>
  );
}
