// Compliance attestations (ADR-0181): fill the OSCAL manual-attestation slots the automated
// collectors can't — a human attests each out-of-band artifact (policy PDF, Object-Lock config,
// pentest report) per framework. Attestations persist tenant-scoped under `withTenant` (RLS). The
// full validate-conformant OSCAL SAR+POA&M export (JSON + XML) is generated by the Compliance edition
// evidence leg from these filled slots; this page owns the human-fill half of that seam.
import type { Metadata } from "next";
import { revalidatePath } from "next/cache";
import { Button, StatusChip } from "@caisson/ui/components";
import {
  AttestationInput,
  COMPLIANCE_FRAMEWORKS,
  attestSlot,
  clearSlot,
  listAttestations,
} from "@/lib/attestations";
import { requireDashboardSession } from "@/lib/auth";

export const metadata: Metadata = { title: "Compliance" };

const PATH = "/dashboard/compliance";

async function attestAction(formData: FormData): Promise<void> {
  "use server";
  const session = await requireDashboardSession(PATH);
  const parsed = AttestationInput.safeParse({
    framework: formData.get("framework"),
    slotId: formData.get("slotId"),
    note: formData.get("note") ?? "",
  });
  if (!parsed.success) return;
  await attestSlot(session.accountId, session.userId, parsed.data);
  revalidatePath(PATH);
}

async function clearAction(formData: FormData): Promise<void> {
  "use server";
  const session = await requireDashboardSession(PATH);
  const parsed = AttestationInput.pick({
    framework: true,
    slotId: true,
  }).safeParse({
    framework: formData.get("framework"),
    slotId: formData.get("slotId"),
  });
  if (!parsed.success) return;
  await clearSlot(session.accountId, parsed.data.framework, parsed.data.slotId);
  revalidatePath(PATH);
}

const inputStyle: React.CSSProperties = {
  fontSize: "var(--cs-text-sm)",
  padding: "var(--cs-space-2) var(--cs-space-3)",
  border: "1px solid var(--cs-border)",
  borderRadius: "var(--cs-radius-md)",
  background: "var(--cs-surface1)",
  color: "var(--cs-fg)",
  minWidth: "28ch",
};

export default async function DashboardCompliancePage() {
  const session = await requireDashboardSession(PATH);

  // One tenant-scoped read per framework (three frameworks, ADR-0181).
  const filledByFramework = new Map<string, Map<string, string>>();
  for (const fw of COMPLIANCE_FRAMEWORKS) {
    const records = await listAttestations(session.accountId, fw.id);
    filledByFramework.set(
      fw.id,
      new Map(records.map((r) => [r.slotId, r.note])),
    );
  }

  return (
    <div style={{ display: "grid", gap: "var(--cs-space-8)" }}>
      <div>
        <h1
          className="cs-card-title"
          style={{ fontSize: "var(--cs-text-2xl)" }}
        >
          Compliance attestations
        </h1>
        <p className="cs-muted" style={{ marginTop: "var(--cs-space-2)" }}>
          Attest the human-provided evidence the automated collectors can&apos;t
          gather. These fill the OSCAL export&apos;s manual slots. The full SAR
          + POA&amp;M bundle (JSON, and XML where the OSCAL CLI is available) is
          generated by the Compliance edition from these attestations —{" "}
          <a
            href="/api/compliance/attestations"
            style={{ color: "var(--cs-accent)" }}
          >
            download your attestation record (JSON)
          </a>
          .
        </p>
      </div>

      {COMPLIANCE_FRAMEWORKS.map((fw) => {
        const filled =
          filledByFramework.get(fw.id) ?? new Map<string, string>();
        return (
          <section
            key={fw.id}
            style={{ display: "grid", gap: "var(--cs-space-4)" }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "var(--cs-space-3)",
              }}
            >
              <h2
                className="cs-card-title"
                style={{ fontSize: "var(--cs-text-lg)", margin: 0 }}
              >
                {fw.title}
              </h2>
              <StatusChip
                label={`${String(filled.size)} / ${String(fw.slots.length)} attested`}
                tone={filled.size === fw.slots.length ? "accent" : "muted"}
                dot
              />
            </div>

            {fw.slots.map((slot) => {
              const isFilled = filled.has(slot.id);
              return (
                <div
                  key={slot.id}
                  style={{
                    display: "grid",
                    gap: "var(--cs-space-2)",
                    padding: "var(--cs-space-4)",
                    border: "1px solid var(--cs-border)",
                    borderRadius: "var(--cs-radius-md)",
                    background: "var(--cs-surface1)",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "var(--cs-space-3)",
                    }}
                  >
                    <StatusChip
                      label={isFilled ? "attested" : "pending"}
                      tone={isFilled ? "accent" : "muted"}
                      dot
                    />
                    <span style={{ fontWeight: 500 }}>{slot.label}</span>
                  </div>

                  <form
                    action={attestAction}
                    style={{
                      display: "flex",
                      gap: "var(--cs-space-3)",
                      alignItems: "flex-end",
                      flexWrap: "wrap",
                    }}
                  >
                    <input type="hidden" name="framework" value={fw.id} />
                    <input type="hidden" name="slotId" value={slot.id} />
                    <label
                      style={{
                        display: "grid",
                        gap: "var(--cs-space-2)",
                        flex: 1,
                      }}
                    >
                      <span
                        className="cs-muted"
                        style={{ fontSize: "var(--cs-text-xs)" }}
                      >
                        Attestation note / artifact reference
                      </span>
                      <input
                        name="note"
                        defaultValue={filled.get(slot.id) ?? ""}
                        maxLength={2000}
                        placeholder="e.g. link to the signed policy PDF, ticket, or reviewer + date"
                        style={inputStyle}
                      />
                    </label>
                    <Button type="submit" variant="primary">
                      {isFilled ? "Update" : "Attest"}
                    </Button>
                  </form>

                  {isFilled && (
                    <form action={clearAction}>
                      <input type="hidden" name="framework" value={fw.id} />
                      <input type="hidden" name="slotId" value={slot.id} />
                      <Button type="submit" variant="ghost">
                        Clear attestation
                      </Button>
                    </form>
                  )}
                </div>
              );
            })}
          </section>
        );
      })}
    </div>
  );
}
