#!/usr/bin/env bash
# Local admin auth harness — stand up an authed apps/admin dev server WITHOUT GitHub OAuth, so the
# visual harness (Playwright shots of authed admin pages) and the security pentest can reach every
# /admin route. apps/admin is GitHub-OAuth-only (ADR-0283); prod can't be scripted, so this runs a
# throwaway loopback Postgres, pins one env file both the session-minter and `bun dev` read, and
# mints a real signed session cookie (apps/admin/scripts/seed-harness-session.ts).
#
#   tools/security/harness-admin.sh up     # start throwaway PG + mint session + print next steps
#   tools/security/harness-admin.sh down   # tear down PG + remove .harness/
#   tools/security/harness-admin.sh env    # print the line to source before `bun dev`
#
# The env file (apps/admin/.harness/env.sh) is generated once with a fresh random secret and REUSED
# across `up` runs so the dev server and the minted cookie always share the same HMAC key. Nothing
# here touches a real DB or real secrets — the whole point is an isolated, disposable stack.
#
# ponytail: `up` does NOT manage the long-running dev server (pidfile/port/log juggling isn't worth
# it) — it prints the exact command. Wrap it in a supervisor if you ever need one-shot CI use.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"

CONTAINER="caisson-admin-harness-pg"
# Loopback host port for the throwaway PG — override CAISSON_HARNESS_PG_PORT if 5433 is taken.
PG_HOST_PORT="${CAISSON_HARNESS_PG_PORT:-5433}"
PG_PORT="127.0.0.1:${PG_HOST_PORT}"
PG_IMAGE="postgres:16-alpine"
HARNESS_DIR="$REPO/apps/admin/.harness"
ENV_FILE="$HARNESS_DIR/env.sh"
DEV_CMD="source apps/admin/.harness/env.sh && bun --cwd apps/admin dev"

write_env() {
  mkdir -p "$HARNESS_DIR"
  [[ -f "$ENV_FILE" ]] && return 0
  local secret
  secret="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  cat > "$ENV_FILE" <<EOF
# Generated by tools/security/harness-admin.sh — throwaway admin-harness env. Git-ignored.
# BOTH the session-minter and \`bun --cwd apps/admin dev\` must source THIS file (same HMAC secret).
export ADMIN_AUTH_DATABASE_URL="postgres://postgres:harness@127.0.0.1:${PG_HOST_PORT}/admin_harness"
export ADMIN_AUTH_DIRECT_DATABASE_URL="\$ADMIN_AUTH_DATABASE_URL"
export ADMIN_BETTER_AUTH_SECRET="$secret"
export ADMIN_BETTER_AUTH_URL="http://localhost:3020"
export ADMIN_GITHUB_ALLOWED_USER_IDS="999999001"
export ADMIN_HARNESS_GITHUB_ID="999999001"
# getAdminAuth() returns null (→ every request denied) unless a GitHub client id/secret pair is
# present; the harness never runs a real OAuth flow, so any non-empty placeholder unblocks it.
export ADMIN_GITHUB_CLIENT_ID="harness"
export ADMIN_GITHUB_CLIENT_SECRET="harness"
EOF
  ok "wrote $ENV_FILE (fresh secret)"
}

pg_up() {
  have docker || { warn "docker required for the throwaway Postgres"; exit 1; }
  if docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    ok "throwaway PG already running ($CONTAINER)"
  else
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    hr "starting throwaway Postgres ($PG_IMAGE on $PG_PORT)"
    docker run --rm -d --name "$CONTAINER" -p "$PG_PORT:5432" \
      -e POSTGRES_PASSWORD=harness -e POSTGRES_DB=admin_harness "$PG_IMAGE" >/dev/null
  fi
  local i
  for i in $(seq 1 30); do
    docker exec "$CONTAINER" pg_isready -U postgres -d admin_harness >/dev/null 2>&1 && { ok "PG ready"; return 0; }
    sleep 1
  done
  warn "PG did not become ready in 30s"; exit 1
}

case "${1:-}" in
  up)
    write_env
    pg_up
    hr "minting admin session"
    # shellcheck source=/dev/null
    set -a; source "$ENV_FILE"; set +a
    bun run "$REPO/apps/admin/scripts/seed-harness-session.ts"
    hr "next steps"
    cat <<EOF
  1. start the authed admin dev server (same env, another shell):
       $DEV_CMD
  2. visual harness (authed admin shots):
       bun --cwd apps/admin run scripts/seed-harness-session.ts   # (already done — storageState is fresh)
       # then point your Playwright run at http://localhost:3020 with apps/admin/.harness/admin-session.json
  3. pentest / DAST against the authed surface:
       tools/security/scan.sh --layer deep --target http://localhost:3020
       # or replay the printed Cookie header with curl / ZAP / nuclei -H
  teardown when done:  tools/security/harness-admin.sh down
EOF
    ;;
  down)
    docker rm -f "$CONTAINER" >/dev/null 2>&1 && ok "removed $CONTAINER" || warn "no $CONTAINER container"
    rm -rf "$HARNESS_DIR" && ok "removed $HARNESS_DIR"
    ;;
  env)
    [[ -f "$ENV_FILE" ]] || { warn "no env file yet — run 'up' first"; exit 1; }
    echo "source apps/admin/.harness/env.sh"
    ;;
  *)
    grep -E '^#( |$)' "$0" | sed 's/^# \?//' | head -20
    exit 2
    ;;
esac
