/**
 * Advisory design-critic ledger (ADR-0099 Layer 3). The critic — a `gw-frontend-designer`-style pass
 * scoring surfaces on the Nielsen rubric — emits findings; this module gives them STABLE IDENTITY and
 * RECONCILES run-to-run so the ledger is durable instead of a fresh dump each time:
 *
 *   - id = sha256(workflow ∷ surface ∷ normalized-title)[:16] — rewording a title never forks a finding.
 *   - reconcile() classifies every id this run: new / unchanged / regressed / closed. A fixed finding
 *     that REAPPEARS flips to `regressed`; an operator-`accepted` finding keeps that status while it
 *     persists; a finding that DISAPPEARS flips to `fixed` (class `closed`).
 *
 * This is strictly NON-BLOCKING (ADR-0099 Binding): a rubric score never gates a merge. The ledger
 * informs the next pass; nothing here exits non-zero.
 */
import { createHash } from "node:crypto";

export type FindingStatus = "open" | "accepted" | "fixed";
export type FindingSeverity = "info" | "warn" | "high";

export interface Finding {
  /** stable, derived — see stableId(). */
  id: string;
  /** the critic pass that surfaced it (e.g. "ui-review", "a11y-audit"). */
  workflow: string;
  /** the screen/component under critique (e.g. "hero", "pricing"). */
  surface: string;
  /** human title; may be reworded run-to-run without forking the id. */
  title: string;
  severity: FindingSeverity;
  status: FindingStatus;
}

/** A freshly-emitted finding before reconcile assigns an id + resolves its status. */
export type RawFinding = Omit<Finding, "id" | "status"> & {
  status?: FindingStatus;
};

export type ReconcileClass = "new" | "unchanged" | "regressed" | "closed";

export interface ReconcileResult {
  /** the merged ledger to persist (sorted by id). */
  ledger: Finding[];
  /** per-id classification for THIS run. */
  classes: Record<string, ReconcileClass>;
}

/** Normalize a title for identity: lowercase, punctuation→space, collapse whitespace. */
function normalizeTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim()
    .replace(/\s+/g, " ");
}

/** Stable ID = sha256(workflow ∷ surface ∷ normalized-title)[:16]. */
export function stableId(
  workflow: string,
  surface: string,
  title: string,
): string {
  return createHash("sha256")
    .update(`${workflow}∷${surface}∷${normalizeTitle(title)}`)
    .digest("hex")
    .slice(0, 16);
}

/** Attach the derived id (+ default status) to a raw finding. */
export function withId(f: RawFinding): Finding {
  return {
    ...f,
    status: f.status ?? "open",
    id: stableId(f.workflow, f.surface, f.title),
  };
}

/**
 * Reconcile a fresh critic run against the persisted ledger. Pure: no IO, deterministic.
 *  - present this run, absent before        → `new`        (status open)
 *  - present this run, was `fixed` before    → `regressed`  (status open — it came back)
 *  - present this run, was open/accepted      → `unchanged`  (status PRESERVED — operator triage sticks)
 *  - absent this run, was open/accepted       → `closed`     (status fixed)
 *  - absent this run, was already `fixed`     → carried forward, no class (stays closed)
 */
export function reconcile(
  previous: Finding[],
  current: RawFinding[],
): ReconcileResult {
  const prev = new Map(previous.map((f) => [f.id, f]));
  const seen = new Set<string>();
  const ledger: Finding[] = [];
  const classes: Record<string, ReconcileClass> = {};

  for (const raw of current) {
    const f = withId(raw);
    seen.add(f.id);
    const p = prev.get(f.id);
    if (!p) {
      classes[f.id] = "new";
      ledger.push({ ...f, status: "open" });
    } else if (p.status === "fixed") {
      classes[f.id] = "regressed";
      ledger.push({ ...f, status: "open" });
    } else {
      classes[f.id] = "unchanged";
      ledger.push({ ...f, status: p.status });
    }
  }
  for (const p of previous) {
    if (seen.has(p.id)) continue;
    if (p.status === "fixed") {
      ledger.push(p);
    } else {
      classes[p.id] = "closed";
      ledger.push({ ...p, status: "fixed" });
    }
  }
  ledger.sort((a, b) => a.id.localeCompare(b.id));
  return { ledger, classes };
}

// ── minimal TOML round-trip for the constrained `[[finding]]` array-of-tables schema ──────────────
// Hand-rolled (no dep): every field is a quoted scalar string, so a tiny parser/serializer is exact
// and deterministic. NOT a general TOML implementation — only this ledger's shape.

const esc = (s: string): string =>
  s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const unesc = (s: string): string =>
  s.replace(/\\"/g, '"').replace(/\\\\/g, "\\");

const LEDGER_HEADER = `# design-critic findings ledger — ADR-0099 Layer 3 (ADVISORY, never blocks a merge).
# Stable id = sha256(workflow ∷ surface ∷ normalized-title)[:16]. status: open | accepted | fixed.
# Regenerated by reconcile(); the operator hand-edits ONLY \`status\` (open→accepted to triage a finding).
`;

export function serializeFindings(ledger: Finding[]): string {
  const tables = [...ledger]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map(
      (f) =>
        `[[finding]]\n` +
        `id = "${f.id}"\n` +
        `workflow = "${esc(f.workflow)}"\n` +
        `surface = "${esc(f.surface)}"\n` +
        `title = "${esc(f.title)}"\n` +
        `severity = "${f.severity}"\n` +
        `status = "${f.status}"\n`,
    );
  return `${LEDGER_HEADER}\n${tables.join("\n")}`;
}

export function parseFindings(toml: string): Finding[] {
  const out: Finding[] = [];
  let cur: Record<string, string> | null = null;
  const flush = () => {
    const c = cur;
    cur = null;
    if (!c) return;
    const { id, workflow, surface, title, severity, status } = c;
    // Truthy-narrow every required field (noUncheckedIndexedAccess → each is string | undefined).
    if (id && workflow && surface && title && severity && status) {
      out.push({
        id,
        workflow,
        surface,
        title,
        severity: severity as FindingSeverity,
        status: status as FindingStatus,
      });
    }
  };
  for (const lineRaw of toml.split("\n")) {
    const line = lineRaw.trim();
    if (line === "" || line.startsWith("#")) continue;
    if (line === "[[finding]]") {
      flush();
      cur = {};
      continue;
    }
    const m = line.match(/^(\w+)\s*=\s*"(.*)"$/);
    if (m && cur && m[1] !== undefined && m[2] !== undefined)
      cur[m[1]] = unesc(m[2]);
  }
  flush();
  return out;
}
